### ISSUE TITLE
MACHINEOVERRIDES issue while RF_FIRMWARES is defined as empty

### ISSUE THREAD

**Issue by Renegade85** [TechNexion/meta-tn-imx-bsp#1]
Hello,

it appears that the MACHINEOVERRIDES from local.conf.sample causes issues, while RF_FIRMWARES is set to empty string, i.e.  **''**. Most probably this will cause issues for sound cards as well.

`MACHINEOVERRIDES =. "${@'' if d.getVar('RF_FIRMWARES', True) is None else '%s:' % ':'.join([fw.lower() for fw in d.getVar('RF_FIRMWARES', True).split(' ') if fw])}"
`
Invoking:
`MACHINE=pico-imx8mq DISTRO=fsl-imx-xwayland source edm-setup-release -b build`

-> We don't put WIFI_FIRMWARES into the build.
Grants the RF_FIRMWARES variables gets set as **RF_FIRMWARES = ''**

Once the MACHINEOVERRIDES as stated above gets evaluated, you end up with empty string replacing **%s: -> ':'** and appending to current MACHINEOVERRIDES
So at the end only a colon is appended to MACHINEOVERRIDES.

Let's say MACHINEOVERRIDES is:

imx:mx8:mx8m

and we expand MACHINEOVERRIDES from above. The result is:

imx:mx8:mx8m:

The colon overrides the FILESPATH and instead of looking into mx8m first, it looks into default directories first. So your patches won't get applied due to this mismatch.

My example was:
imx:mx8:mx8m:imxdrm:imxdcss:imxvpu:imxvpuhantro:imxgpu:imxgpu3d:mx8mq:**voicehat::pico-imx8mq**:aarch64

It appears the double colon here represents the default path, so patches from defaults if any get applied before patches from mx8mq. But the defaults should be applied as last...

**Comment by po-cheng-technexion** [comment]
Fix on the next branch
commit f735ea794a4cd7ea35ce254f6def47b1a959631e

**Comment by Renegade85** [comment]
Thank you for the fast reply. When do you plan to release it into stable branch?

**Comment by po-cheng-technexion** [comment]
We are planning to release in the Next Quarter,
meanwhile, feel free to remove those codes from local.conf.sample because those machine overrides are now resides in tn-base.inc, which is dedicated to TechNexion machine configs.

**Comment by Renegade85** [comment]
Thank you very much for the info. I'll try it out and in case of any issues report back the result.
