### ISSUE TITLE
Automate Accepting EULA LICENSE in case of Devops requirement 

### ISSUE THREAD

**Issue by ankit-lathiya** [TechNexion/meta-tn-imx-bsp#12]

**Comment by ankit-lathiya** [comment]
`tn-setup-release.sh` is having manual steps for accepting the EULA fsl license.

**Comment by ankit-lathiya** [comment]
@johnweber can you please help me on this

**Comment by ankit-lathiya** [comment]
We want some hack to automate this since in the case of DevOps manual accepts of license is not possible

**Comment by richard-hu** [comment]
@ankit-lathiya :

 The step can be skipped by putting `ACCEPT_FSL_EULA = "1"` in `conf/local.conf`
 
 BR,

Richard
