### ISSUE TITLE
attempts to build glmark2 break DISTRO=fsl-imx-fb

### ISSUE THREAD

**Issue by gizero** [TechNexion/meta-tn-imx-bsp#3]
While testing recent changes in `sumo_4.14.98-2.0.0_GA-next` I run into an issue 
that seems to be related to commit 79e52eb31f8618eff209fc86f17b503af0b7e8f6. This commit is adds glmark2 to `RDEPENDS_${PN}` for `thermal-imx-test` recipe. This is raising issues when building images (i.e. fsl-image-qt5) with `DISTRO=fsl-imx-fb`, because no backend flavour ends up being configured for glmark2 at build time. I can try to fix it and send a patch, but I'd like someone to advice where this should be best fixed. Shall we add more condition to exclude `thermal-imx-test` from the packagegroup in `packagegroup-tn-tools.bb`?

**Comment by richard-hu** [comment]
@gizero 

Thanks for you kind feedback.
It's probably my bad. 

Could you share the command you use to configure Yocto?
```
e.g. 
WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-fb MACHINE=pico-imx7 BASEBOARD=pi source edm-setup-release.sh -b build-x11-pico-imx7
```

> I can try to fix it and send a patch, but I'd like someone to advice where this should be best fixed.

I would appreciate if you can send us a patch. 
But it should be our task. Don't want it to waste your time. 
Let me check it later.

> Shall we add more condition to exclude thermal-imx-test from the packagegroup in packagegroup-tn-tools.bb?

Wise advice. I should check it carefully.
Let me check how we can make it flexible to adapt to different kind of graphic backends.



BR,

Richard

**Comment by gizero** [comment]
Hi @richard-hu!

Thanks for your quick reply,

> Could you share the command you use to configure Yocto?

Here are the configuration bits I'm using: 
`DISPLAY=lcd DISTRO=fsl-imx-fb MACHINE=pico-imx6 BASEBOARD=pi source edm-setup-release.sh -b build-fb`

> I would appreciate if you can send us a patch.
> But it should be our task. Don't want it to waste your time.
> Let me check it later.
>
> > Shall we add more condition to exclude thermal-imx-test from the packagegroup in packagegroup-tn-tools.bb?
> 
> Wise advice. I should check it carefully.
> Let me check how we can make it flexible to adapt to different kind of graphic backends.

I'd be happy to discuss and/or review any solution you come up with. Graphics backend it's tricky in OE/Yocto and we should all work together to have better BSP layers that also play nice with others.

**Comment by richard-hu** [comment]
@gizero 

I made a patch as the attachment to add `glmark2` conditionally in `thermal-imx-test_git.bb`.
[add_glmarks_conditionally.zip](https://github.com/TechNexion/meta-tn-imx-bsp/files/4238733/add_glmarks_conditionally.zip)

I test the build and it fixes the build problem caused by glmark2.

The build error results from the lack of `gl` package.
> /home/jenkins/server/yocto_development/yocto_2.5_sumo_new_repo_next/build-fb-pico-imx7/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/glmark2/2017.07+AUTOINC+ed20c633f1-r0/git/build/config.log
Checking for 'gl'
['/home/jenkins/server/yocto_development/yocto_2.5_sumo_new_repo_next/build-fb-pico-imx7/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/glmark2/2017.07+AUTOINC+ed20c633f1-r0/recipe-sysroot-native/usr/bin/pkg-config', '--cflags', '--libs', 'gl']
err: Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found

`gl` package is added when `DISTRO_FEATURES` includes `x11` or `wayland`.
If it's OK, i will submit the patch to git repo. :)

BR,

Richard

**Comment by gizero** [comment]
@richard-hu sorry for my late reply. Couldn't make to it until now. I'm not sure your patch goes in the right direction. If I remember correctly `thermal-imx-test` does always require `glmark2`. I haven't noticed any internal condition to run some scripts without it being available. So I expect your patch to deliver a broken package by dropping `glmark2` from `RDEPENDS`.

To work around the original issue, I choose to conditionally pull `thermal-imx-test` in from `packagegroup-tn-tools.bb` only when it makes sense (i.e. required backends are available).

See https://github.com/gizero/meta-tn-imx-bsp/commit/d0975465c8174878386a3b1eccdbe3a5cd940ba5

If you are ok with this approach, let me know and I'll be happy to open a PR.

**Comment by richard-hu** [comment]
@gizero 

Thanks for your advice~

Your patch looks nice. :)
`thermal-imx-test` is used for our internal test.
Both patches solve the compilation error.
But your patch is better, and it prevents from user runs gpu stress of `thermal-imx-test` without `glmark2`
(I should make gpu stress test to be independent of `thermal-imx-test`. 
e.g. Create a new package called `thermal-imx-gpu-test`.)

If you don't mind i would apply your nice patch in TechNexion `meta-tn-imx-bsp`.

If there is no further discussion, i will close this thread.  :)



BR,

Richard

**Comment by gizero** [comment]
@richard-hu feel free to merge https://github.com/TechNexion/meta-tn-imx-bsp/pull/4

**Comment by richard-hu** [comment]
@gizero 

Thanks for your kind reply.
I already merge your patch into TechNexion internal git repo.
After our CI server validates the build, we will synchronize internal git repo to TechNexion github repo.

We appreciate your feedback and advice. :)

BR,

Richard

**Comment by gizero** [comment]
Hi @richard-hu, 

Do you have any timeline for this to land into GitHub public branches? I'm building off my personal fork to overcome the issue, but I'd like to be able to switch back to official repo as soon as possible. Thanks!

**Comment by richard-hu** [comment]
@gizero 

Thanks for your remind.
The Yocto build completes on our internal build server. 
I just update it to github repo: Yocto TechNexion BSP meta-layer `next` branch.
https://github.com/TechNexion/meta-tn-imx-bsp/commits/sumo_4.14.98-2.0.0_GA-next

If there is any problem, please feel free to contact us. :)

BR,

Richard

**Comment by gizero** [comment]
Thanks @richard-hu. Changes in sumo_4.14.98-2.0.0_GA-next do solve the original issue. One last question before finally closing this one. What's your strategy for merging *-next branches into the official GA? Is there any documentation on timelines or any reference for this?

**Comment by richard-hu** [comment]
@gizero 

Sorry for the late reply...
For our current plan,  we would merge `-next` to `-stable` branch every 3 months after our test team validates the release image.

Our test team just completes the release of 2019Q4(2019/12/31). 
So we will release it in the following weeks.

Meanwhile, we are preparing the next BSP release for 2020Q1(2020/3/31).

BR,

Richard

**Comment by gizero** [comment]
Ok @richard-hu, thanks for the info. I think this issue can be closed now.
