### ISSUE TITLE
 imx7d-pico Yocto thud 2.6 not have ethernet conection

### ISSUE THREAD

**Issue by patusaembedded** [TechNexion/meta-tn-imx-bsp#5]
Hi,

I have this issue:
 https://hub.mender.io/t/issues-with-systemd-networkd/2302
I need ethernet/yocto/x11 in imx7d-pico to  a new comercial project.
How can I solve ?

**Comment by richard-hu** [comment]
Hello, @patusaembedded :

TechNexion official BSP doesn't provide Yocto thud 2.6.
It looks Yocto thud 2.6 is from Yocto community.
TechNexion officaial latest stable Yocto release is Yocto sumo 2.5.
https://github.com/TechNexion/tn-imx-yocto-manifest/tree/sumo_4.14.y_GA-stable
I believe that ethernet works fine in TechNexion Yocto sumo 2.5.
ftp://ftp.technexion.net/demo_software/PICO/IMX7/pico-imx7-emmc/DiskImage/pico-imx7_pico-pi_yocto-2.5-qt5_qca9377_lcd-800x480_20200825.zip


From the screenshot you post in mender, it looks the ethernet PHY is initialized properly.
What kind of network manager you use in Yocto thud 2.6 (`network manager` or `connman`)?
(Usually, Yocto uses `connman` as default network manager)

```Using ConnMan to Configure wired interfaces

To get the list of wired interfaces run
# connmanctl services
For example:
# connmanctl services
*AO Wired                ethernet_0eb31468dcc9_cable
Wired interfaces will be shown as ethernet_<mac_address>_cable. Only interfaces physically connected to the network are displayed.
To create static IP configuration run
# connmanctl config <service> --ipv4 manual <ip address> <netmask> <gateway>
# connmanctl config <service> --nameservers <dns-addr> 

For example:
# connmanctl config ethernet_0eb31468dcc9_cable --ipv4 manual 192.168.1.100 255.255.255.0 192.168.1.254
# connmanctl config ethernet_0eb31468dcc9_cable --nameservers 8.8.8.8 4.4.4.4 
```

BR,

Richard

**Comment by patusaembedded** [comment]
@richard-hu tks. I stay using systemd-networkd. Lines 264-267 of the my local.conf  https://gist.github.com/patusaembedded/ce9dd70a289747d2109f4c654cd009af

I tried several things in the tutorial below, but it didn't work:
 https://hub.mender.io/t/how-to-configure-networking-using-systemd-in-yocto-project/1097

What I need to change in my local.conf to solve my issue? How to solve my issue ? How to use connman in my 2.6 (thud) Yocto project

**Comment by johnweber** [comment]
Hi @patusaembedded, can you please send an email to me john.weber@technexion.com to further discuss your problem?

**Comment by johnweber** [comment]
Closing. We didn't implement support for Yocto 2.6 (Thud).
