### ISSUE TITLE
PICO-PI IMX.8MQ:  20210207.1 Bitbake issues

### ISSUE THREAD

**Issue by Kabuto15** [TechNexion/meta-tn-imx-bsp#6]
I faced issues when trying to bitbake the latest release. I guess linux-tn-src_4.14.98.inc  and SRC_REV is pointing to "next" branch instead of the "stable".

`ERROR: linux-tn-imx-4.14.98-r1 do_fetch: Fetcher failure: Unable to find revision e8f3bd5f2db6fef62a73bf97c05fab3387990fb7 in branch tn-imx_4.14.98_2.0.0_ga-stable even from upstream`

edm_yocto/sources/meta-tn-imx-bsp/recipes-kernel/linux/linux-tn-src_4.14.98.inc
SRCREV = "e8f3bd5f2db6fef62a73bf97c05fab3387990fb7"

**Comment by po-cheng-technexion** [comment]
Kernel -stable Branch update with latest -next Branch commits
