### ISSUE TITLE
[PICO-PI-IMX7]  Splash screen not showing on LCD when u-boot start

### ISSUE THREAD

**Issue by pino-kim** [TechNexion/meta-tn-imx-bsp#7]
**Description**
This issue is derived from https://github.com/TechNexion/u-boot-tn-imx/issues/4
Power on PICO-PI-IMX7,  Splash screen not showing on LCD when u-boot start.

**Steps to reproduce the issue:**
```
$ repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b zeus_5.4.y-next -m imx-5.4.70-2.3.0.xml
$ DISTRO=fsl-imx-x11 MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-x11-pico-imx7 
$ bitbake core-image-base

And flash it on the board and power on.
```

**Describe the results you received:**
 Splash screen showing on LCD with TechNexion's logo image when u-boot start.

**Additional information you deem important

**Additional details**
 * Target : PICO-PI-IMX7
 * LCD : TDP0500T800480PCAP

Attach the video with power on to boot up finish

https://user-images.githubusercontent.com/29390119/133881879-6f17d7aa-73da-4c7e-851e-01c935d810b2.mp4

**Comment by yoooh8668** [comment]
Hi Pino,

Our lastest u-boot can support splash screen with pico-imx7d.
Here is the commit hash:
**d1db4ce46f2088bfe72b84d5337cb18f339f2905**
**pico-imx7d: add splash screen support**

**06baed80d210b61ca710072af672dc22bc007ae4**
**pico-imx7d: add u-boot logo support**

**7f584b866290da1f4d677f0c57e0f0d209f15fbe**
**driver: commom: remove the static attribute of show_default_logo api**

You can try `repo sync` to your yocto project.
Please copy the boot log if the issue remains.

THANKS~~~~
Joe

**Comment by pino-kim** [comment]
@yoooh8668 

Thanks for the comment.
Check your git hash id and start the rebuild. 
I hope you have a great weekend ^^
