### ISSUE TITLE
[PICO-PI-IMX7] Report build fail at hardknott_5.10.52-2.1.0-next

### ISSUE THREAD

**Issue by pino-kim** [TechNexion/meta-tn-imx-bsp#8]
**Description**
**PICO-PI-IMX7** yocto builds failed at the **hardknott_5.10.52-2.1.0-next** branch

**Steps to reproduce the issue:**
```
$ mkdir tn-imx-yocto
$ cd tn-imx-yocto
$ repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.52-2.1.0.xml
$ repo sync -j8
$ DISTRO=fsl-imx-x11 MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-x11-pico-imx7
$ bitbake -k core-image-base
```

**Describe the results you received:**
Build success

**Describe the results you expected:**
Build failed 2 package
* linux-tn-imx : do_compile ([linux-tn-imx_do_compile.log](https://github.com/TechNexion/meta-tn-imx-bsp/files/7448133/linux-tn-imx_do_compile.log))
* uboot : do_configure ([uboot_do_configure.log](https://github.com/TechNexion/meta-tn-imx-bsp/files/7448135/uboot_do_configure.log))

**Additional information you deem important (e.g. issue happens only occasionally):**
* linux-tn-imx_do_compile.log 
 ```
/home/pino/workspace/Opensource/tn-imx-yocto/build-x11-pico-imx7/tmp/work-shared/pico-imx7/kernel-source/drivers/gpu/drm/vivante/vivante_drv.c:52:10: fatal error: drm/drmP.h: No such file or directory
   52 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
/home/pino/workspace/Opensource/tn-imx-yocto/build-x11-pico-imx7/tmp/work-shared/pico-imx7/kernel-source/scripts/Makefile.build:280: recipe for target 'drivers/gpu/drm/vivante/vivante_drv.o' failed
make[5]: *** [drivers/gpu/drm/vivante/vivante_drv.o] Error 1
/home/pino/workspace/Opensource/tn-imx-yocto/build-x11-pico-imx7/tmp/work-shared/pico-imx7/kernel-source/scripts/Makefile.build:497: recipe for target 'drivers/gpu/drm/vivante' failed
make[4]: *** [drivers/gpu/drm/vivante] Error 2
/home/pino/workspace/Opensource/tn-imx-yocto/build-x11-pico-imx7/tmp/work-shared/pico-imx7/kernel-source/scripts/Makefile.build:497: recipe for target 'drivers/gpu/drm' failed
make[3]: *** [drivers/gpu/drm] Error 2
/home/pino/workspace/Opensource/tn-imx-yocto/build-x11-pico-imx7/tmp/work-shared/pico-imx7/kernel-source/scripts/Makefile.build:497: recipe for target 'drivers/gpu' failed
make[2]: *** [drivers/gpu] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC      lib/crc-ccitt.o
  CC      lib/crc16.o
  AR      drivers/tty/built-in.a
/home/pino/workspace/Opensource/tn-imx-yocto/build-x11-pico-imx7/tmp/work-shared/pico-imx7/kernel-source/Makefile:1824: recipe for target 'drivers' failed
make[1]: *** [drivers] Error 2
make[1]: *** Waiting for unfinished jobs....
 ```

* uboot_do_configure.log
```
***
*** Can't find default configuration "arch/../configs/pico-imx7d_spl_defconfig"!
***
/home/pino/workspace/Opensource/tn-imx-yocto/build-x11-pico-imx7/tmp/work/pico_imx7-poky-linux-gnueabi/u-boot-tn-imx/2021.04-r0/git/scripts/kconfig/Makefile:110: recipe for target 'pico-imx7d_spl_defconfig' failed
```

**Additional details (revisions used, host distro, etc.):**
* build environment
```
Build Configuration:
BB_VERSION           = "1.50.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "pico-imx7"
DISTRO               = "fsl-imx-x11"
DISTRO_VERSION       = "5.10-hardknott"
TUNE_FEATURES        = "arm vfp cortexa7 neon thumb callconvention-hard"
TARGET_FPU           = "hard"
meta
meta-poky            = "HEAD:14c5392fded42f17962e1cc07fcc0446881b4fa0"
meta-oe
meta-multimedia
meta-python          = "HEAD:5a4b2ab29d38c02535f24d5308cc40615739f557"
meta-freescale       = "HEAD:2027a8045384463b7c793381dd887b0591037e2f"
meta-freescale-3rdparty = "HEAD:060967a7df43e8505568aa3d54fd8addcecab98d"
meta-freescale-distro = "HEAD:916df6d24c0a33a3b1533bde70b6a2724ec77af4"
meta-bsp
meta-sdk
meta-ml
meta-v2x             = "HEAD:426311a3f4e6936125c0599a34d8f6133dd2460d"
meta-nxp-demo-experience = "HEAD:71d85758f4189a065e69b10527e4014e998d0a80"
meta-gnome
meta-networking
meta-filesystems     = "HEAD:5a4b2ab29d38c02535f24d5308cc40615739f557"
meta-python2         = "HEAD:8db9e4f6ceae33d7a4f55453d31e69f9858af4eb"
meta-chromium        = "HEAD:8be1d3a0ba0cf32e61144900597207af5698c10d"
meta-clang           = "HEAD:7ef47d048267cf755c496a3962b34314f6f1f1e1"
meta-qt5             = "HEAD:a00af3eae082b772469d9dd21b2371dd4d237684"
meta-tn-imx-bsp      = "HEAD:46155700ea84ba5e6950631127ca5c54523bc3ec"
meta-nxp-nfc         = "HEAD:5d05c57fc8faf3f1bc95c1702e1a6aa78d83412f"
```

**Comment by richard-hu** [comment]
@pino-kim :

Thanks for your feedback.
The porting job is on-going on latest hardknott_5.10.52-2.1.0-next branch.
ARM64 platforms will be supported first.(i.mx8mp -> i.mx8mm -> i.mx8mq -> imx8mn)
Then we will start the porting job on ARM32. (i.mx6 -> i.mx7d -> i.mx6ul)
PICO-PI-IMX7 will be supported later. (probably around end of this year.)

BR,

Richard

**Comment by pino-kim** [comment]
@richard-hu,

Thanks for comment my issue.

So I still waiting.

**Comment by pino-kim** [comment]
Hi, @richard-hu

ARM32(imx6, imx7) porting is still on going?

**Comment by richard-hu** [comment]
Hi, @pino-kim :

We just complete the u-boot for PICO-IMX7D.
https://github.com/TechNexion/u-boot-tn-imx/commit/7835e231153bd2866fb8fa2dc3e9203a7589076c

I will try to create a Yocto build for PICO-IMX7D.
Let me check it we can make an early preview version for you.

BR,

Richard

**Comment by pino-kim** [comment]
Oh hi, @richard-hu 

It's good news.

I 'm happy to wait next preview version. 

Thanks.

**Comment by richard-hu** [comment]
@pino-kim :

I make a quick porting for pico-imx7d.
It looks fine. 
I already push all the patches about linux and yocto bsp meta-layer for pico-imx7d to TN github: 

https://github.com/TechNexion/linux-tn-imx/tree/tn-imx_5.10.52_2.1.0-next
https://github.com/TechNexion/meta-tn-imx-bsp/tree/hardknott_5.10.52-2.1.0-next

Here is the Yocto 3.3 pre-built image for pico-imx7d:
https://download.technexion.com/.to_customer/imx-image-multimedia-pico-imx7-20211210090155.rootfs.wic.bz2

> repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.52-2.1.0.xml
> 
> repo sync -j8
> 
> WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-xwayland MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-fsl-imx-xwayland-pico-imx7
> 
> bitbake imx-image-multimedia

BTW, NXP just releases lf-5.10.72-2.2.0 BSP. This is the version we aim at for the next TechNexion software stable release.
https://source.codeaurora.org/external/imx/linux-imx/log/?h=lf-5.10.y

tn-imx_5.10.52_2.1.0-next branch will be archived in the near future.
All existing work will migrate to tn-imx_5.10.72_2.2.0-next branch.

Hope you can enjoy development on PICO-IMX7D.

Thanks~!!!

BR,

Richard

**Comment by pino-kim** [comment]
@richard-hu 
Wow, nice work.
I was really surprised that the kernel and u-boot port work was done so quickly. 

Also, 
Thanks for sending me the pre-built image too.
So, Am I possible to make the same image with the below command?

```
$ mkdir tn-imx-yocto && cd tn-imx-yocto
$ repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.52-2.1.0.xml
$ repo sync -j8
$ WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-xwayland MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-fsl-imx-xwayland-pico-imx7
$ bitbake imx-image-multimedia
```

Thanks

**Comment by pino-kim** [comment]
@richard-hu 
Build success,

```
$ mkdir tn-imx-yocto && cd tn-imx-yocto
$ repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.52-2.1.0.xml
$ repo sync -j8
$ WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-xwayland MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-fsl-imx-xwayland-pico-imx7
$ bitbake imx-image-multimedia
```

This issue is about imx7d build fail
So, I close this issue

by the way,
When is the official release date of hardknott_5.10.y-next ? (predictably)

Thanks

**Comment by richard-hu** [comment]
@pino-kim :

Originally, we expect to release hardknott_5.10.y-next in end of December.
But it seems we are behind the schedule.

The worst case is we will release hardknott_5.10.y-next(based on `tn-imx_5.10.72_2.2.0-next`) in January.
The time estimation is for all TechNexion products.

`PICO-IMX7D` should be supported after we migrate all the work to new Yocto hardnott branch.
The `-next` branch of Yocto hardknott will be kept updating weekly.


BR,

Richard

**Comment by pino-kim** [comment]
@richard-hu 

Thanks for your kind reply

> But it seems we are behind the schedule.

It's fine. I understand it and can wait for the official release. 

I wish you all a great time in the end of 2021.

cheers

sungwon.pino

**Comment by patusaembedded** [comment]
pLease help-me I try this: 

$ mkdir tn-imx-yocto && cd tn-imx-yocto
$ repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.52-2.1.0.xml
$ repo sync -j8
$ WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-xwayland MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-fsl-imx-xwayland-pico-imx7
$ bitbake imx-image-multimedia


The current situation is as follows:

1) I have an antenna connected, I haven't installed drivers and I don't have wifi.

2) USB input only accept mouse and not keyboard

**and mainly:**

3) I don't have an internet connection via ethernet, as shown in the photo below:

![issue2](https://user-images.githubusercontent.com/71419485/146084833-385151ff-e710-4c26-a046-3d48f41bbbcc.png)

**Comment by pino-kim** [comment]
@patusaembedded 
This issue is close.
How about opening another issue?
